### Question 5

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import numpy.linalg as npla
import scipy.linalg as spla

In [2]:
def moving(i,j,action):
    # action direction : upwards=2, downwards=3, left=1, right=0
    newi = 0
    newj = 0
    reward = 0
    # move from A to A'
    if i==0 and j==1:
        newi = 4
        newj = 1
        reward = 10
    # move from B to B'
    elif i==0 and j==3:
        newi = 2
        newj = 3
        reward = 5
    #corners
    # at row=0, cannot move upwards
    elif i==0 and action==2:
        newi = i
        newj = j
        reward = -1
    # at row=4, cannot move downwards
    elif i==4 and action==3:
        newi = i
        newj = j
        reward = -1
    # at column=0, cannot move left
    elif j==0 and action==1:
        newi = i
        newj = j
        reward = -1
    # at column=4, cannot move right
    elif j==4 and action==0:
        newi = i
        newj = j
        reward = -1
    else:
        # move right
        if action==0:
            newi = i
            newj = j+1
            reward = 0
        # move left
        elif action==1:
            newi = i
            newj = j-1
            reward = 0
        # move upwards
        elif action==2:
            newi = i-1
            newj = j
            reward = 0
        # move downwards
        elif action==3:
            newi = i+1
            newj = j
            reward = 0
            
    return newi, newj, reward

In [3]:
# Initializing number of states, number of actions, gridSize and gamma
num_states = 25
num_actions = 4
gamma = 0.9
gridSize = 5

# additiveVpi represents summation over all actions a, pi(a|s)*reward obtained from each action, for all states s
# coeffVpi represents summation over all actions a, pi(a|s)*gamma, for all states s
# vpi represents value function for each state s under policy pi
additiveVpi = np.zeros(num_states)
coeffVpi = np.zeros((num_states,num_states))
vpi = np.zeros((gridSize,gridSize))

for i in range(0,gridSize):
    for j in range(0,gridSize):
        # term2 would hold the summation over all actions pi(a|s)*reward obtained from each action, for state (i,j)
        term2 = np.zeros((gridSize,gridSize))
        term2[i,j]=-1
        # term1 would hold the summation over all actions a, pi(a|s)*gamma for state (i,j)
        term1 = 0
        
        # action direction : upwards=2, downwards=3, left=1, right=0
        for action in range(0,num_actions):
            # new state (newi,newj) obtained after moving from state (i,j) under action and reward represents the 
            # corresponding reward
            newi,newj,reward = moving(i,j,action)
            
            # pi(a|s) = 1/4 as pi picks actions in a state with equal probability
            term1 += reward/4
            term2[newi,newj] += gamma/4
        
        additiveVpi[gridSize*i+j] = term1
        tempstorage = np.zeros(num_states)
        i1 = 0
        for l1 in range(0,gridSize):
            for l2 in range(0,gridSize):
                tempstorage[i1] = term2[l1,l2]
                i1 += 1
        coeffVpi[gridSize*i+j] = tempstorage

additiveVpi *= -1
temp = np.linalg.solve(coeffVpi,additiveVpi)
ind = 0
for i in range(0,gridSize):
    for j in range(0,gridSize):
        vpi[i,j] = round(temp[ind],1)
        ind += 1

In [4]:
print(vpi)

[[ 3.3  8.8  4.4  5.3  1.5]
 [ 1.5  3.   2.3  1.9  0.5]
 [ 0.1  0.7  0.7  0.4 -0.4]
 [-1.  -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2. ]]
