### Question 7

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import numpy.linalg as npla
import scipy.linalg as spla
from scipy.optimize import fsolve

In [2]:
def moving(i,j,action):
    # action direction : upwards=2, downwards=3, left=1, right=0
    newi = 0
    newj = 0
    reward = 0
    # move from A to A'
    if i==0 and j==1:
        newi = 4
        newj = 1
        reward = 10
    # move from B to B'
    elif i==0 and j==3:
        newi = 2
        newj = 3
        reward = 5
    #corners
    # at row=0, cannot move upwards
    elif i==0 and action==2:
        newi = i
        newj = j
        reward = -1
    # at row=4, cannot move downwards
    elif i==4 and action==3:
        newi = i
        newj = j
        reward = -1
    # at column=0, cannot move left
    elif j==0 and action==1:
        newi = i
        newj = j
        reward = -1
    # at column=4, cannot move right
    elif j==4 and action==0:
        newi = i
        newj = j
        reward = -1
    else:
        # move right
        if action==0:
            newi = i
            newj = j+1
            reward = 0
        # move left
        elif action==1:
            newi = i
            newj = j-1
            reward = 0
        # move upwards
        elif action==2:
            newi = i-1
            newj = j
            reward = 0
        # move downwards
        elif action==3:
            newi = i+1
            newj = j
            reward = 0
            
    return newi, newj, reward

In [3]:
def optimalValueFunction(vpi):
    valuefun = np.zeros((gridSize, gridSize))
    # converting form 1d to 2d array
    temp = np.zeros((gridSize,gridSize))
    ind = 0
    for i in range(0,gridSize):
        for j in range(0,gridSize):
            temp[i,j] = vpi[ind]
            ind += 1
    vpi = temp
    
    for i in range(0,gridSize):
        for j in range(0,gridSize):
            # maxcoeff represents maximum over all actions, reward obtained from choosing action to get new state s'
            # + gamma * vpi(s')
            maxcoeff = 0
            for action in range(0,num_actions):
                # new state (newi,newj) obtained after moving from state (i,j) under action and reward represents the 
                # corresponding reward
                newi,newj,reward = moving(i,j,action)
                tempstorage = reward + gamma*vpi[newi,newj]
                maxcoeff = max(maxcoeff, tempstorage)
            valuefun[i,j] = vpi[i,j] - maxcoeff
    #converting 2d array to 1d
    temp1 = np.zeros(num_states)
    ind1 = 0
    for i in range(0,gridSize):
        for j in range(0,gridSize):
            temp1[ind1] = valuefun[j,i]
            ind1 += 1
    valuefun = temp1
    return valuefun

In [4]:
def optimalPolicy(vopt):
    # piopt represents the optimal policy
    piopt = np.zeros((gridSize,gridSize))
    for i in range(0,gridSize):
        for j in range(0,gridSize):
            # maxcoeff represents maximum over all actions, reward obtained from choosing action to get new state s'
            # + gamma * vpi(s')
            # maximizingaction represents the action that achieves maxcoeff, ties are broken with larger action being picked 
            # eg, if action 1 and 3 achieve maxcoeff then action 3 is selected as maximizingaction
            maxcoeff = 0
            maximizingaction = 0
            for action in range(0,num_actions):
                newi,newj,reward = moving(i,j,action)
                tempstorage = reward + gamma*vopt[newi,newj]
                if(tempstorage>=maxcoeff):
                    maxcoeff = tempstorage
                    maximizingaction = action
            piopt[i,j] = maximizingaction
    return piopt

In [5]:
# Initializing number of states, number of actions, gridSize and gamma
num_states = 25
num_actions = 4
gamma = 0.9
gridSize = 5

vpi = np.zeros((gridSize,gridSize))
vopt = np.zeros((gridSize,gridSize))
vopttemp = fsolve(optimalValueFunction,vpi)
ind = 0
for i in range(0,gridSize):
    for j in range(0,gridSize):
        vopt[i,j] = round(vopttemp[ind],1)
        ind += 1
print("Optimal value function: ")
print(vopt)
piopt = optimalPolicy(vopt)
print("Optimal policy: (upwards=2, downwards=3, left=1, right=0)")
print(piopt)

Optimal value function: 
[[22.  24.4 22.  19.4 17.5]
 [19.8 22.  19.8 17.8 16. ]
 [17.8 19.8 17.8 16.  14.4]
 [16.  17.8 16.  14.4 13. ]
 [14.4 16.  14.4 13.  11.7]]
Optimal policy: (upwards=2, downwards=3, left=1, right=0)
[[0. 3. 1. 3. 1.]
 [2. 2. 2. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
